//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kategori_resim
    {
        public int k_resim_id { get; set; }
        public string k_resimad { get; set; }
        public Nullable<bool> k_durum { get; set; }
        public Nullable<int> kategori_id { get; set; }
    
        public virtual kategoriler kategoriler { get; set; }
    }
}
