//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class qrpandemenu_Entities : DbContext
    {
        public qrpandemenu_Entities()
            : base("name=qrpandemenu_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<ceolar> ceolar { get; set; }
        public virtual DbSet<kategori_resim> kategori_resim { get; set; }
        public virtual DbSet<kategoriler> kategoriler { get; set; }
        public virtual DbSet<resim> resim { get; set; }
        public virtual DbSet<restaurant> restaurant { get; set; }
        public virtual DbSet<subeLogo> subeLogo { get; set; }
        public virtual DbSet<urunler> urunler { get; set; }
        public virtual DbSet<teklif> teklif { get; set; }
    }
}
