//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class resim
    {
        public int resimid { get; set; }
        public string resimad { get; set; }
        public Nullable<bool> durum { get; set; }
        public Nullable<int> urunid { get; set; }
    
        public virtual urunler urunler { get; set; }
    }
}
