//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subeLogo
    {
        public int logoid { get; set; }
        public string logoad { get; set; }
        public Nullable<bool> durum { get; set; }
        public Nullable<int> subeid { get; set; }
    
        public virtual restaurant restaurant { get; set; }
    }
}
