//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class teklif
    {
        public int id { get; set; }
        public string isim { get; set; }
        public string email { get; set; }
        public string tel { get; set; }
        public string mesaj { get; set; }
        public Nullable<bool> ifread { get; set; }
    }
}
