//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public urunler()
        {
            this.resim = new HashSet<resim>();
        }
    
        public int urunid { get; set; }
        public string urunadi { get; set; }
        public string urunfiyat { get; set; }
        public string urunaciklama { get; set; }
        public int kategoriid { get; set; }
        public Nullable<int> rest_id { get; set; }
        public Nullable<int> use_id { get; set; }
    
        public virtual admin admin { get; set; }
        public virtual kategoriler kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<resim> resim { get; set; }
        public virtual restaurant restaurant { get; set; }
    }
}
